[package]
name = "seaplane"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Seaplane IO, Inc."]

[dependencies]
serde = {version = "1.0", features = ["derive"]}
thiserror = "1.0"
