name: Security Audit
on:
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
  - cron: '42 4 * * 2'
  workflow_dispatch:

jobs:
  security_audit:
    name: Security Audit
    container: rust:slim
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Install Build Deps (Linux)
      run: apt-get update && apt-get install -y git libssl-dev pkg-config

    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
