name: Security Audit
on:
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
  - cron: '42 4 * * 2'
  workflow_dispatch:

jobs:
  security_audit:
    name: Run a rust security audit
    runs-on: [self-hosted, linux, arm64, lxc]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
