# CI workflow for every merge to main.
#
# This workflow may also be triggered manually for testing purposes.
name: Merge to main

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-pr-workflow-lib:
    uses: ./.github/workflows/workflow-pr.yml
    with:
      manifest_path: ./seaplane/Cargo.toml

  call-pr-workflow-cli:
    uses: ./.github/workflows/workflow-pr.yml
    with:
      manifest_path: ./seaplane-cli/Cargo.toml

  call-ui-test-workflow:
    uses: ./.github/workflows/workflow-ui-test.yml

  call-api-test-workflow:
    uses: ./.github/workflows/workflow-api-test.yml
