# CI workflow for every merge to main.
#
# This workflow may also be triggered manually for testing purposes.
name: Merge to Main

on:
  push:
    branches: [main]
    paths:
    - 'seaplane-cli/**/*.rs'
    - 'seaplane-sdk/rust/**/*.rs'
    - 'seaplane-sdk/python/**/*.py'
    - .github/workflows/merge.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-rust-tests:
    uses: ./.github/workflows/workflow-rust-tests.yml
    with:
      test_sdk: true
      test_cli: true

  run-python-tests:
    uses: ./.github/workflows/workflow-python-tests.yml
