# CI workflow for every merge to main.
#
# This workflow may also be triggered manually for testing purposes.
name: "Rust merge to main"

on:
  push:
    branches: [main]
    paths:
    - 'seaplane-sdk/rust/**'
    - 'seaplane-cli/**'
    - .github/workflows/merge.yml
    - '!**.md'
    - '!docs/**'
    - '!share/**'
    - "!LICENSE"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-rust-tests:
    uses: ./.github/workflows/workflow-rust-tests.yml
    with:
      test_sdk: true
      test_cli: true
