name: CLI Pull Request CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'seaplane-cli/**'
      - .github/workflows/pr-cli.yml
      - .github/workflows/workflow-rust-tests.yml
      - '!**.md'
      - '!docs/**'
      - '!share/**'
      - "!LICENSE"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-rust-cli-tests:
    uses: ./.github/workflows/workflow-rust-tests.yml
    with:
      test_sdk: false
      test_cli: true
