name: CLI PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'seaplane-cli/**/*.rs'
      - 'seaplane-cli/Cargo.toml'
      - .github/workflows/pr-cli.yml
      - .github/workflows/workflow-rust-tests.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-rust-cli-tests:
    uses: ./.github/workflows/workflow-rust-tests.yml
    with:
      test_sdk: false
      test_cli: true
