name: Lib OID PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'crates/oid/**/*.rs'
      - .github/workflows/pr-libs-oid.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-rust-crate-tests:
    uses: ./.github/workflows/workflow-rust-tests.yml
    with:
      test_sdk: false
      test_cli: false
      test_lib_container_image_ref: false
      test_lib_oid: true
