name: Python SDK PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'seaplane-sdk/python/**/*.py'
      - 'seaplane-sdk/python/pyproject.toml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-rust-cli-tests:
    uses: ./.github/workflows/workflow-python-tests.yml
    with:
