name: Rust SDK Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'seaplane-sdk/rust/**/*.rs'
      - 'seaplane-sdk/rust/Cargo.toml'
      - .github/workflows/pr-sdk-rust.yml
      - .github/workflows/workflow-rust-tests.yml
      - '!**.md'
      - '!docs/**'
      - "!LICENSE"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-rust-cli-tests:
    uses: ./.github/workflows/workflow-rust-tests.yml
    with:
      test_sdk: true
      test_cli: false
