on:
  push:
    tags:
      - 'v*'

name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-win-x64:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['windows-latest']"
      target: x86_64-pc-windows-gnu
      use-tag-version: true

  # build-mac-x64:
  #   uses: ./.github/workflows/workflow-build-release.yml
  #   with:
  #     runner: "['macos-latest']"
  #     target: x86_64-apple-darwin
  #     use-tag-version: true

  build-linux-x64-gnu:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      use-tag-version: true

  build-linux-aarch64-gnu:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['self-hosted', 'linux', 'arm64']"
      target: aarch64-unknown-linux-gnu
      use-tag-version: true

  release:
    name: Create Release
    runs-on: [self-hosted, linux, x64]
    container: ubuntu:focal
    needs:
      - build-win-x64
      - build-linux-x64-gnu
      - build-linux-aarch64-gnu
        #- build-mac-x64
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Download all workflow release artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Seaplane v${{ steps.get_version.outputs.VERSION }}
          files: artifacts/artifact/seaplane-*.tar.gz
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_REPOSITORY: seaplane-io/seaplane
