on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  get_version:
    container: ubuntu:focal
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

  build-win-x64:
    needs: get_version
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['windows-latest']"
      target: x86_64-pc-windows-gnu
      bin-id: ${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}

  build-mac-x64:
    needs: get_version
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['macos-latest']"
      target: x86_64-apple-darwin
      bin-id: ${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}

  # TODO: when M1 Runner is ready
  # build-mac-aarch64:
  #   needs: get_version
  #   uses: ./.github/workflows/workflow-build-release.yml
  #   with:
  #     runner: "['self-hosted', 'arm64', 'macOS']"
  #     target: aarch64-apple-darwin
  #     bin-id: ${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}

  build-linux-x64-gnu:
    needs: get_version
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      bin-id: ${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}

  # build-linux-x64-musl:
  #   needs: get_version
  #   uses: ./.github/workflows/workflow-build-release.yml
  #   with:
  #     target: x86_64-unknown-linux-musl
  #     bin-id: ${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}

  build-linux-aarch64-gnu:
    needs: get_version
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['self-hosted', 'linux', 'arm64']"
      target: aarch64-unknown-linux-gnu
      bin-id: ${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}

  # build-linux-aarch64-musl:
  #   needs: get_version
  #   uses: ./.github/workflows/workflow-build-release.yml
  #   with:
  #     runner: "['linux', 'arm64']"
  #     target: aarch64-unknown-linux-musl
  #     use-cross: true
  #     bin-id: ${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}

  release:
    name: Create Release
    runs-on: [self-hosted, linux, x64]
    container: ubuntu:focal
    needs:
      - get_version
      - build-win-x64
      - build-mac-x64
      - build-linux-x64-gnu
      - build-linux-aarch64-gnu
        #- build-mac-aarch64
        #- build-linux-x64-musl
        #- build-linux-aarch64-musl
    steps:
      - name: Download all workflow release artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Seaplane (${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }})
          files: |
            seaplane-${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
            seaplane-${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}-aarch64-unknown-linux-gnu.tar.gz
            seaplane-${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}-x86_64-pc-windows-gnu.tar.gz
            seaplane-${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}-x86_64-apple-darwin.tar.gz
            # seaplane-${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}-aarch64-apple-darwin.tar.gz
            # seaplane-${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}-x86_64-unknown-linux-musl.tar.gz
            # seaplane-${{ needs.jobs.get_version.steps.get_version.outputs.VERSION }}-aarch64-unknown-linux-musl.tar.gz
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_REPOSITORY: seaplane-io/seaplane
