on:
  push:
    tags:
      - 'cli-v*'
  workflow_dispatch:

name: Seaplane CLI Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-win-x64:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['windows-latest']"
      use-tag-version: true

  build-linux-x64-gnu:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['self-hosted', 'linux', 'x64']"
      use-tag-version: true

  build-linux-aarch64-gnu:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['self-hosted', 'linux', 'arm64']"
      use-tag-version: true

  # Currently we build by hand to sign and notarize the builds
  # build-mac-x64:
  #   uses: ./.github/workflows/workflow-build-release.yml
  #   with:
  #     runner: "['macos-latest']"
  #     use-tag-version: true

  release:
    name: Release
    runs-on: [self-hosted, linux, x64]
    container: ubuntu:focal
    needs:
      - build-win-x64
      - build-linux-x64-gnu
      - build-linux-aarch64-gnu
        #- build-mac-x64
    steps:
      - name: Download all workflow release artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: seaplane-${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/artifact/seaplane-cli-v*.tar.gz
            artifacts/artifact/seaplane-cli-v*.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_REPOSITORY: seaplane-io/seaplane

