# This workflow may also be triggered manually for testing purposes.
name: Javascript Tests Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: seaplane-sdk/javascript
    strategy:
      matrix:
        node-version: [18.x, 19.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        architecture: x64
    - run: npm ci
    - run: npm run lint

  tests:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: seaplane-sdk/javascript
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        architecture: x64
    - run: npm ci
    - run: npm run build
    - run: npm test
