name: Pull Request CI

on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        features: ["--no-default-features", "", "--features unstable"]
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo test ${{ matrix.features }} --manifest-path ${{ inputs.manifest_path }} --no-run --all-targets

    - name: Test
      run: cargo test ${{ matrix.features }} --manifest-path ${{ inputs.manifest_path }}



